import os
import glob
import FWCore.ParameterSet.Config as cms
from TTH.MEAnalysis.samples_base import *
import ROOT

cmssw_base = os.environ["CMSSW_BASE"]

version = "Jun23_leptonic_v1"
datasetpath = "src/TTH/MEAnalysis/gc/datasets/{0}/".format(version)
getSize = False

path1 = os.path.join(cmssw_base, datasetpath)
samples = [ os.path.splitext(os.path.basename(s))[0] for s in glob.glob(os.path.join(path1,"*.txt"))]
print samples

sampfiles = {}
samples_dict = {}

samp_py = open("samples.py", "w")

samp_py.write("# THIS IS AN AUTOGENERATED FILE\n")
samp_py.write("# Made by prepareSamples.py\n")
samp_py.write("# do NOT modify (except to skip individual samples)\n\n\n")

samp_py.write('import FWCore.ParameterSet.Config as cms\n')
samp_py.write('from TTH.MEAnalysis.samples_base import *\n\n')

samp_py.write('version = "' + version + '"\n')
samp_py.write('datasetpath = "' + datasetpath + '"\n')

samp_py.write("samples_dict = {\n")
for sample in samples:

    isMC = True
    if "Single" in sample or "Double" in sample or "MuonEG" in sample:
        isMC = False
    
    x = """ 
        "{0}": cms.PSet(
            name     = cms.string("{0}"),
            nickname = cms.string("{0}"),
            isMC     = cms.bool({1}),
            treeName = cms.string("vhbb/tree"),
            subFiles = cms.vstring(get_files(datasetpath + "{0}.txt")),
        ),
    """.format(sample, isMC)
    samp_py.write(x)

samp_py.write("}\n")
samp_py.close()
